apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-large-spot
spec:
  replicas: 5
  selector:
    matchLabels:
      app: inflate-large-spot
  template:
    metadata:
      labels:
        app: inflate-large-spot
    spec:
      containers:
      - image: mcr.microsoft.com/oss/kubernetes/pause:3.6
        name: inflate
        resources:
          requests:
            cpu: "5"
            memory: 256M
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: inflate-large-spot
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "karpenter.sh/capacity-type"
                operator: In
                values:
                - "spot"
