apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate-small-gpu
spec:
  replicas: 5
  selector:
    matchLabels:
      app: inflate-small-gpu
  template:
    metadata:
      labels:
        app: inflate-small-gpu
    spec:
      containers:
      - image: mcr.microsoft.com/oss/kubernetes/pause:3.6
        name: inflate
        resources:
          requests:
            cpu: "1"
            memory: 256M
          limits:
           nvidia.com/gpu: 1
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: inflate-small-gpu